name: CI-coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.26
          php_extensions: xdebug
          bootstrap: html/vendor/autoload.php
          configuration: html/test/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
